$('.owl-carousel').owlCarousel({
    loop:true,
    margin:32,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:false
        },
        600:{
            items:3,
            nav:false
        },
    }
})